### ISSUE TITLE
just  can pushNotification by laster 10.0 ios?

### ISSUE THREAD

**Issue by luwenbin1991** [GREENBANYAN/PushNotificationManager#1]
Can Adaptation of earlier than 10.0?

**Comment by GREENBANYAN** [comment]
Unless you're using the new features in iOS 10 like attachment，you can use it normally.Remember to remove budge after receiving the notification，I forgot to do this in the example.

**Comment by apdevzhang** [comment]
Unless you're using the new features in iOS 10 like attachment，you can use it normally.Remember to remove budge after receiving the notification，I forgot to do this in the example.
